# Database Configuration File

# MongoDB Configuration
mongodb:
  host: localhost
  port: 27017
  # username: "radium_admin"
  # password: "YKYr5vCpKPZxM5loU7TWAbVU"
  database: "radium"

# Redis Configuration
redis:
  host: localhost
  port: 6379
  username: "default"
  password: "P3XWLBKRFpEROPqaLfq7JKyn"